### ISSUE TITLE
system hangs during boot on Thinkpad X201

### ISSUE THREAD

**Issue by proger** [TritonDataCenter/smartos-live#26]
manual tracing led me to clear_boot_mappings() called from release_bootstrap().

However I'm not sure whether this was caused by callout/interrupt activity, but the crash is always reproducible in that place.  

![screenshot](http://i.imgur.com/6khWV.jpg)

**Comment by travispaul** [comment]
Due to the age of this ticket and the inability to easily reproduce I'm going to go ahead and resolve it.
