### ISSUE TITLE
ZFS kstat is missing "recycle_miss" key and breaks arcstat cmd

### ISSUE THREAD

**Issue by sigxcpu76** [TritonDataCenter/smartos-live#391]
Release 20141225T170427Z

``` console
# kstat -m zfs -p | grep recycle
zfs:0:arcstats:recycle_miss     74068
#
```

Release 20150123T200224Z

``` console
# kstat -m zfs -p | grep recycle
#
```

Error

``` console
# arcstat
    time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  arcsz     c
Use of uninitialized value in division (/) at /usr/bin/arcstat line 329.
10:52:07     0     0      0     0    0     0    0     0    0    12G   12G
```

`arcstat` problem line

``` console
# head -n 329 /usr/bin/arcstat | tail -n 1
        $v{"rmiss"} = $d{"recycle_miss"}/$int;
```

**Comment by rmustacc** [comment]
Thanks, it looks like this was introduced by 5497 lock contention on arcs_mtx (244781f10dcd82684fd8163c016540667842f203) upstream. I'll bring it up with them and we'll try to get this sorted promptly.

**Comment by rmustacc** [comment]
Upstream bug https://www.illumos.org/issues/5564 has been filed. We'll leave this open to track the integration and merge of that change.

**Comment by xen0l** [comment]
@rmustacc  This has been fixed and can be closed.
