### ISSUE TITLE
p7zip commands silently truncated terminal-entered passwords to 8 characters

### ISSUE THREAD

**Issue by whorfin** [TritonDataCenter/smartos-live#999]
Using
```
https://pkgsrc.joyent.com/packages/SmartOS/trunk/x86_64/All
```
on 
```
$ uname -a
SunOS serverbox 5.11 omnios-r151038-c078b41acd i86pc i386 i86pc illumos
```
and having installed `p7zip` 

I find that long entered passwords are silently truncated to 8 characters...

Basically, because Solaris crippled `getpass()`, `getpassphrase()` should be called instead on Illumos.

Same behavior is observed with the omnios-native
```
 pkg:/compress/p7zip@16.2-151038.0
```

Reported to omnios-build:
https://github.com/omniosorg/omnios-build/issues/2457

Reported to "upstream" p7zip:
https://sourceforge.net/p/p7zip/bugs/230/

The p7zip report includes a very simple fix.

**Comment by bahamat** [comment]
Can you file this in the [pkgsrc](/joyent/pkgsrc) repo?

**Comment by travispaul** [comment]
Going to go ahead and resolve this issue since it's also been opened in the pkgsrc project.
